### ISSUE TITLE
Error in library(Rcpi)

### ISSUE THREAD

**Issue by EmanIsmail** [nanxstats/Rcpi#3]
I installed Rcpi with the following:
source("http://bioconductor.org/biocLite.R")
biocLite("Rcpi")
and I get error there is no package called ‘Rcpi’??

**Comment by nanxstats** [comment]
Hi @EmanIsmail - there could be many reasons but here is my guess: please run this again and check the outputs from the installation -- maybe some dependencies of the package have not been successfully installed due to missing system libraries: for example, ChemmineR, rcdk (which requires rJava and JDK).
