### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by psterk** [nanxstats/Rcpi#6]
In the documentation, under
3.1 Regression Modeling in QSRR Study of Retention Indices

There appears to be an error in the following code:

library("Rcpi")

RI.smi = system.file(
  "vignettedata/FDAMDD.smi", package = "Rcpi")
RI.csv = system.file(
  "vignettedata/RI.csv", package = "Rcpi")

Shouldn't the first file to be loaded be RI.smi instead of FDAMDD.smi? The train step does not work otherwise.

Best wishes.

**Comment by nanxstats** [comment]
Hi @psterk -that's a good catch! Thanks. I don't know how FDAMDD got up there... but this has just been fixed in https://github.com/road2stat/Rcpi/commit/79f94e06f88bf31282150bfb20269f4f954b51b7 and the docs site is updated.

You're welcome to try the GitHub version. I also push the new version to Bioconductor release/devel, and it may take a day or two for it to be available there.
